[book]
authors = ["Aaron Erhardt"]
language = "en"
multilingual = false
src = "src"
title = "GUI development with Relm4"

[output.html]
git-repository-url = "https://github.com/AaronErhardt/AaronErhardt.github.io/tree/master/relm4-book"
git-repository-icon = "fa-github"
