name: blog

on:
  push:
    branches:
      - blog  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.0'

      - name: Build
        run: hugo --minify
        working-directory: ./

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/blog') || github.event_name == 'release' || github.event_name == 'workflow_dispatch' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: false
          destination_dir: ./blog
